name: Financial Audit
run-name: financial-audit
on: [push]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t financial-audit .
      - name: Run container
        run: docker run -d -p 3000:3000 financial-audit
