name: Financial Audit
run-name: financial-audit
on: [push]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Call Audit API
        run: |
          # Wait for the container to be ready
          sleep 10
          # Call the audit API
          curl -X GET https://lazo-interview.onrender.com/audit
